### ISSUE TITLE
可以增加生成 compiledb 的功能吗？

### ISSUE THREAD

**Issue by liangz678** [xmake-io/.github#10]
### 你在什么场景下需要该功能？

可以增加生成 compiledb 的功能吗？以便 cland 调用
这样 nvim 的 lsp 才能正常工作

### 描述可能的解决方案

增加生成 compiledb 的功能

**Comment by waruqi** [comment]
不是原本就支持么，仔细看文档，另外不要提到这里，到对应 repo 下的 issues 里面反馈。。

https://xmake.io/#/zh-cn/plugin/builtin_plugins?id=%e7%94%9f%e6%88%90compiler_commands
https://xmake.io/#/zh-cn/plugin/more_plugins?id=%e9%85%8d%e7%bd%ae-intellsence
